[package]
name = "kflowd-common"
version = "0.1.0"
edition = "2021"

[dependencies]
# Updated for aya 0.13.1 compatibility
aya-bpf = { version = "0.2.0", features = ["macros"] }
libc = "0.2"

[lib]
crate-type = ["lib"]
