[package]
name = "dirt_rs-ebpf"
version = "0.1.0"
edition = "2021"

[dependencies]
dirt_rs-common = { path = "../dirt_rs-common" }

aya-ebpf = { workspace = true }
aya-log-ebpf = { workspace = true }

[build-dependencies]
which = { workspace = true }

[[bin]]
name = "dirt_rs"
path = "src/main.rs"
